/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'bg-black',
    'text-white',
    'text-cyan-400',
    'text-purple-400',
    'text-green-400',
    'text-yellow-400',
    'text-red-400',
    'bg-cyan-400',
    'bg-purple-400',
    'bg-green-400',
    'bg-yellow-400',
    'bg-red-400',
    'border-cyan-400',
    'border-purple-400',
    'border-green-400',
    'border-yellow-400',
    'border-red-400',
    'from-cyan-400',
    'to-purple-400',
    'from-purple-400',
    'to-cyan-400',
    'from-green-400',
    'to-emerald-400',
    'from-red-400',
    'to-pink-400',
    'from-gray-400',
    'to-slate-400',
    'from-yellow-400',
    'to-orange-400',
    'bg-gradient-to-r',
    'bg-gradient-to-br',
    'backdrop-blur-xl',
    'animate-pulse',
    'animate-ping',
    'hover:scale-105',
    'hover:scale-110',
    'transition-all',
    'duration-300',
    'font-black',
    'tracking-wider',
    'bg-clip-text',
    'text-transparent'
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
} 